.TH man_1_simple_shell 1 "2024 - 08 - 17" "1.0" "shell manual"

.SH NAME
hsh - Holberton-SHell

.SH SYNOPSIS
.B #include "shell.h"
.sp
.B ./hsh [options] [file]
.sp
.B #cisfun /bin/comand [options] [file]

.SH DESCRIPTION
hsh is a simple shell designed to provide fundamental shell functionalities.

.SH EXAMPLES

.B ./hsh
#cisfun$ ls

.SH REFERENCES
.sp
.BR bash (1)
