.TH man_1_simple_shell 1 "2024 - 08 - 17" "1.0" "shell manual"

.SH NAME
simple shell - designed to provide fundamental shell functionalities.

.SH SYNOPSIS
.B #include "main.h"
.sp
.B ./hsh
.sp
.B #cisfun /bin/comand

.SH DESCRIPTION
.\" Aquí va la descripción de tu shell.

.SH EXAMPLES
.\" Aquí van ejemplos de uso.

.SH REFERENCES
.sp
.BR bash (1)
